import React from 'react';
import Link from 'next/link';

const PrivacyPage = () => {
  return (
    <div className="bg-dark-bg min-h-screen text-white p-4 sm:p-6 lg:p-8 flex flex-col items-center">
      <div className="w-full max-w-4xl flex flex-col">
        <header className="text-center w-full mb-8">
          <Link href="/">
            <h1 className="text-3xl sm:text-4xl md:text-5xl font-bold text-solana-green" style={{ textShadow: '3px 3px 0px #B069FF' }}>
              Trenchmon Card Generator
            </h1>
          </Link>
        </header>
        <main className="w-full bg-card-bg border-2 border-border-color rounded-lg shadow-lg p-6 md:p-8 text-light-gray">
          <h2 className="text-2xl sm:text-3xl font-bold text-solana-green mb-6 text-center">Privacy Policy</h2>
          <div className="space-y-4 text-sm md:text-base leading-relaxed">
            <p>Last Updated: July 26, 2024</p>
            <p>Welcome to the Trenchmon Card Generator. We respect your privacy and are committed to protecting it. This Privacy Policy explains what information we process when you use our service.</p>
            
            <h3 className="text-xl font-bold text-solana-purple pt-4">1. Information We Process</h3>
            <p><strong>Images You Upload:</strong> When you upload an image, it is sent to our server and then to Google's AI services (Gemini and Imagen APIs) to generate the Trenchmon card. We do not store your original uploaded images on our servers after the generation process is complete.</p>
            <p><strong>Generated Content:</strong> The card data and artwork generated by the AI are temporarily processed to be displayed to you and allow you to download the final card image. We do not permanently store this generated content.</p>

            <h3 className="text-xl font-bold text-solana-purple pt-4">2. How We Use Information</h3>
            <p>Your uploaded image is used solely as input for the AI models. They are not used for any other purpose, sold to third parties, or used for training models outside of Google's standard API terms.</p>

            <h3 className="text-xl font-bold text-solana-purple pt-4">3. Data Storage and Security</h3>
            <p>We do not create user accounts and do not have a database to store personal information or your uploaded/generated content. The entire process is ephemeral. While we do not store your data, the transmission of information via the internet is not completely secure. We rely on standard HTTPS protocols to protect data in transit.</p>
            
            <h3 className="text-xl font-bold text-solana-purple pt-4">4. Third-Party Services</h3>
            <p>Our service relies on Google's Gemini and Imagen APIs. When you upload an image, it is subject to Google's privacy policy and terms of service. We recommend you review <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer" className="text-solana-green hover:underline">Google's Privacy Policy</a> to understand how they handle data.</p>
            
            <h3 className="text-xl font-bold text-solana-purple pt-4">5. Changes to This Policy</h3>
            <p>We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes.</p>
            
            <h3 className="text-xl font-bold text-solana-purple pt-4">6. Contact Us</h3>
            <p>If you have any questions about this Privacy Policy, please feel free to reach out to us through our project's contact channels (if available).</p>
          </div>
          <div className="text-center mt-8">
            <Link href="/" className="w-full sm:w-auto inline-block px-6 py-3 bg-solana-purple text-white font-bold rounded-md transition-all duration-200 ease-in-out hover:bg-solana-purple/80 active:scale-95">
                Back to Generator
            </Link>
          </div>
        </main>
      </div>
    </div>
  );
};

export default PrivacyPage;